<?php

return [
    'en-GB'  => 'English (UK)',
    'ar-AE'  => 'Arabic',
    'az-AZ'  => 'Azerbaijani (Azerbaijan)',
    'cmn-CN' => 'Chinese (Mandarin)',
    'hr-HR'  => 'Croatian (Croatia)',
    'cs-CZ'  => 'Czech (Czech Republic)',
    'da-DK'  => 'Danish (Denmark)',
    'nl-NL'  => 'Dutch (Netherlands)',
    'en-US'  => 'English (USA)',
    'et-EE'  => 'Estonian (Estonia)',
    'fi-FI'  => 'Finnish (Finland)',
    'fr-FR'  => 'French (France)',
    'de-DE'  => 'German (Germany)',
    'el-GR'  => 'Greek (Greece)',
    'he-IL'  => 'Hebrew (Israel)',
    'hi-IN'  => 'Hindi (India)',
    'hu-HU'  => 'Hungarian (Hungary)',
    'is-IS'  => 'Icelandic (Iceland)',
    'id-ID'  => 'Indonesian (Indonesia)',
    'it-IT'  => 'Italian (Italy)',
    'ja-JP'  => 'Japanese (Japan)',
    'kk-KZ'  => 'Kazakh (Kazakhstan)',
    'ko-KR'  => 'Korean (South Korea)',
    'lt-LT'  => 'Lithuanian (Lithuania)',
    'ms-MY'  => 'Malay (Malaysia)',
    'mk-MK'  => 'Macedonian (North Macedonia)',
    'nb-NO'  => 'Norwegian (Norway)',
    'fa_IR'  => 'Persian',
    'pl-PL'  => 'Polish (Poland)',
    'pt-BR'  => 'Portuguese (Brazil)',
    'pt-PT'  => 'Portuguese (Portugal)',
    'ro-RO'  => 'Romanian (Romania)',
    'ru-RU'  => 'Russian (Russia)',
    'sk-SK'  => 'Slovak (Slovakia)',
    'sl-SI'  => 'Slovenian (Slovenia)',
    'es-ES'  => 'Spanish (Spain)',
    'es-MX'  => 'Spanish (Mexico)',
    'sw-KE'  => 'Swahili (Kenya)',
    'sv-SE'  => 'Swedish (Sweden)',
    'tr-TR'  => 'Turkish (Turkey)',
    'th-TH'  => 'Thai (Thailand)',
    'vi-VN'  => 'Vietnamese (Vietnam)',
    'uk-UA'  => 'Ukrainian (Ukraine)',
];
